package:
  name: unittest2
  version: "1.1.0"

source:
  fn: unittest2-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/u/unittest2/unittest2-1.1.0.tar.gz
  md5: f72dae5d44f091df36b6b513305ea000
  patches:
    - remove-argparse.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - unit2 = unittest2.__main__:main_

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argparse # [py26]
    - traceback2

  run:
    - python
    - argparse # [py26]
    - six >=1.4
    - traceback2

test:
  # Python imports
  imports:
    - unittest2.case

  commands:
    - unit2 --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/unittest2
  license: BSD License
  summary: 'The new features in unittest backported to Python 2.4+.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
